<?php
/**
 * @package SGEOBIZ_SEO\Views\Sitemap\XSL\Styles
 * @subpackage SGEOBIZ_SEO\Sitemap\XSL
 */

namespace SGEOBIZ_SEO;

( \defined( 'SGEOBIZ_SEO_PRESENT' ) and Helper\Template::verify_secret( $secret ) ) or die;

use SGEOBIZ_SEO\Helper\Format\Markdown;

// phpcs:disable WordPress.WP.GlobalVariablesOverride -- This isn't the global scope.

/**
 * SGEOBIZ SEO plugin
 * Copyright (C) 2021 - 2025 SGEOBIZ (https://sgeobiz.com/)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published
 * by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

?>
<p>
	<?php
	// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- convert_markdown escapes.
	echo Markdown::convert(
		/* translators: URLs are in Markdown. */
		\esc_xml( \__( 'Generated by [SGEOBIZ SEO](https://sgeobiz.com/)', 'sgeobiz-seo' ) ),
		[ 'a' ],
		[ 'a_internal' => false ],
	);
	?>
</p>
